export const STORY_SCENE_REALIZATION = [
  "Narration speaks. Scene description stages the scene itself — a lived moment the viewer could watch — never camera, lens, lighting, shot size, movement, or generation syntax.",
  "sceneDescription must obey the locked Hook: Scene 1 visual withholds what scene1Withholds and openingQuestion leave open. Scene description must withhold what scene1Withholds and openingQuestion leave open.",
  "Do not invent a proxy object (card, tag, sign, arrow, or floating UI) merely because an abstract method or number is hard to visualize; keep objects the Atom or locked story actually names; keep objects the Atom or locked story names.",
  "Scene realization: Scene Description is the strongest visible story event that expresses the Purpose in this particular beat. First decide the story event, not the information. First decide: what is the story event, rather than the information being communicated? Prefer direct human/object/world action over explanatory representations when both communicate the same meaning. A screen, interface, document, chart, card, or diagram is appropriate only when it is itself part of the story event. A screen or interface is appropriate only when it is itself the story event. Preserve the current unresolved question and reveal only the evidence this beat has earned. Before finalizing Scene Description, ask: am I showing the story event or explaining the information?",
  "Three-mode staging follows the locked eventMode. physical_comparison stages the physical alternatives and the comparing action — not a listing, laptop, phone, or shopping UI. mediated_surface may show the named information surface because that surface is the story event. dual may show both only because Purpose named both.",
  "Scene Description robustness: write as many sentences as the moment needs — typically four to seven — consistent with situationLock, staging the full moment: one specific lived-in place you commit to; who is present, how much of them is visible, and what they physically do; the story subjects in concrete visible form — what kind of objects the viewer actually sees; the mood and tension as felt atmosphere, not a lighting recipe; and what stays unresolved. A one-line caption is a defect. A sentence that repeats another field or adds no new visible detail is also a defect — density, never padding. Do not write camera, lighting, or material-finish recipes here.",
  "Verbalize the locked humanPresenceConstraint. person names face and substantial upper-body presence in frame, that person a primary subject. partial names a face with attached torso context, without requiring a full figure. hands names only the hands and forearms. none names no person. A line that only says someone holds the alternatives, with no visibility amount, is a defect when the lock is person or partial. Still no lens, lighting, crop coordinates, wardrobe, décor, or unnamed materials.",
  "If a sentence merely states information printed on a label or screen, rewrite it as a person's action around that information. Reserve generic for unnamed people only — never as a product adjective.",
  "Place, people, and mood are non-claim staging, never new facts. Visual embodiment may show a generic person or ordinary situation when that adds no new factual claim. Audience and customerMoment say why the viewer cares; they do not choose the visual channel. Do not invent named customers, testimonials, medical outcomes, or fabricated drama as fact. Do not invent product-part locations, packaging geography, or store layout the Atom does not name. If the Atom names a panel or field, point to that only when eventMode is mediated_surface or dual and this beat has earned that surface — never on a Scene 1 withhold comparison. Do not invent where else a number lives.",
].join("\n");
