export const STORY_SPOKEN_LANGUAGE = [
  "The Atom gives facts, not wording. Rebuild every spoken line from scratch as you would say it to one person. Preserve the claim — never the sentence, and never the Atom's name for a thing: call each recurring thing by what the viewer sees or does with it, not by a compound noun.",
  "Spoken lock fields: write openingQuestion, payoff, beats[].job, and hookWhy as you would SAY them.",
  "Spoken first-hearing language: narration is a story a smart first-time listener can follow in one pass. Ordinary words first. One new idea per scene. Narration budget: at most 2 sentences and 22 words. A definition never travels with its implication — convert definitions into consequences. A fact appears only in the scene where it changes what the viewer understands, never earlier. Frame as a realization unfolding, not a verdict announced. Prefer the Atom’s strongest useful way of seeing the subject. Translate Atom research phrasing into spoken story — do not recite tension, desiredTakeaway, or decisionQuestion wording. If a technical term is required, explain it in the same breath. Speak to one viewer. Not a children's-show voice. Not a label-instructor voice.",
  "Spoken rewrite pairs (same transformation, different domains — copy the move, not the nouns): “The published arrival window is a carrier-defined interval, not proof both trips share the same clock.” → “Both can say tomorrow morning and still mean different hours.” “Confirm the declared scope before treating the two quotes as comparable.” → “Make sure both quotes cover the same work. Then compare the price.” “The dated event is not proof the two accounts describe the same turning point.” → “Same year on the page can still be two different stories.”",
  "Avoid these constructions: “X is not a Y”; “X is the unit/measure/term that…”; passive verdicts such as “is being judged”; three-technical-noun clauses. Internal planning may use precise analytical concepts. Spoken story must translate them. In spoken fields (narration, on-screen text, jobs, payoff, openingQuestion), avoid like-for-like, like with like, on that basis, fair basis. Say the consequence in ordinary words.",
  "Translate analytical comparison language into ordinary spoken language.",
  "On-screen text labels or teases without spoiling Scene 1’s unresolved question. Do not make all three say the same thing.",
].join("\n");

