export const PRODUCTION_EMBODIMENT = [
  "Never invent explanatory props — tags, cards, signs, arrows, or floating UI — to explain a relationship, number, or comparison. Objects appear only when the locked story names them or the physical situation plainly requires them.",
  "Express relationships through embodiment and staging; never invent explanatory props, tags, cards, or UI to caption an idea.",
  "Express a relationship through staging: placement, relative scale, interaction, simultaneous visibility, and visual hierarchy — not through objects that caption the idea.",
  "Prefer a mid-action or held-tension moment, whichever the beat needs. A decision beat may hold a pause; do not force motion that clips anatomy at the frame edge. Show the situation happening or held, not displayed.",
  "When a beat needs a human or hand cue, decide first whether that cue is useful. If yes, state: the gesture's narrative job (reaching, holding, pausing before a choice, comparing, setting down); how much of the hand or figure is visible; where it enters the frame; that the crop is designed, not an accidental edge clip. Natural anatomy. The hand must not steal the centre of interest or look detached. Some beats need no hands. POV or anonymous hands satisfy the hands lock only. They are illegal when the lock is partial or person.",
  "Anatomical ownership scales to how much body the plate shows. On a hands or hands-and-forearms plate, prove ownership by one unambiguous limb entering from a single named direction with its cut line stated at wrist or forearm, and say the rest of the figure sits outside the frame by design. On a partial-body or full-person plate, prove ownership through continuous shoulder-to-wrist anatomy. Either way, never imply a second off-camera or POV person unless the locked situation stages one.",
  "Decide the head every time a torso is visible: either the whole head sits inside the frame with stated space above it, or the figure is cut at a named line below the collarbone. A skull or face sliced by the top edge is a rendering failure, never a directed crop.",
  "When a face or figure appears, cast it for this beat: presentation, grooming, and wardrobe as situation-appropriate dress chosen from Purpose and place — not a beauty, youth, or luxury default — and an expression sized to the beat's feeling, not a stock smile. Casting is non-claim: no biography, no named identity, and never infer ethnicity, religion, disability, or other sensitive traits. Never sexualize by default.",
  "When the centre of interest is a relationship between alternatives, distinguish them in the picture — slight asymmetry, angle, depth, spacing, or emphasis, with one slightly forward — so the viewer grasps an unresolved choice, not two identical nouns side by side. Do not resolve the choice.",
  "Allowed neutral staging: a specific ordinary lived-in place implied by the locked situation, with one or two non-claim lived-in cues that do atmosphere work; a generic hand or unnamed person as a staging tool; generic unnamed objects that read as real things in a real place (weight, contact shadows, wear) — not studio packshots in a void; ordinary non-claim room light. Neutral means no factual claim, not flat design — the light must still be deliberately shaped. These embody the event. They add no new claim.",
  "Forbidden factual invention: a named store or city the story did not give; brand marks; packaging claims, dosage, or label numbers the Atom/story did not name; a medical setting the story did not give; a named customer, relationship, or testimonial that changes meaning.",
  "A generic person or ordinary situation is allowed when it adds no new factual claim. Do not invent product-part locations, packaging geography, or store layout the Atom did not name.",
].join("\n");
