export const PRODUCTION_SITUATION_FIDELITY = [
  "When situationLock is present, eventMode, requiredSubjects, visibleActionOrState, and relationship are WHAT. Do not reinvent them. Crop, distance, angle, light, materials, and 9:16 bands are HOW. A product adjective such as generic or unbranded in Scene Description does not lock cheap finish.",
  "Read eventMode as the machine channel. Do not infer channel from Scene Description or Atom wording. physical_comparison forbids inventing a laptop, phone, shopping UI, or listing card. mediated_surface may realize the named information surface; do not add a second device. dual allows both the physical alternatives and the named surface. When eventMode is absent on an older board, do not invent a device unless the locked subjects already name one.",
  "Scene Description's place, people, subjects, and action are binding staging. Do not relocate the scene, re-stage the action, or swap subjects. You add framing, light design, optics, depth, materials, and continuity on top of that staging.",
  "locationConstraint and humanPresenceConstraint: open means the staging in Scene Description was the story pass's free choice — keep it for coherence. A set constraint is story-required — keep it exactly. Direct only what Scene Description and situationLock leave unstated.",
  "Do not replace a locked physical story situation with a screen, interface, card, chart, document, diagram, or other mediating surface unless the approved story requires that representation.",
  "When Scene Description stages no person and humanPresenceConstraint is open, choose the lightest human involvement that makes the locked relationship immediately legible: none, hands, partial body, or person. Do not add a human by default. Do not skip a human when the relationship is otherwise unreadable.",
  "humanPresenceConstraint is exclusive floor and ceiling. none: no human may appear. hands: only hands and forearms may appear; a face or torso is illegal. partial: an identifiable person must stay visible, including a face with attached upper-body context; a full figure is not required. person: a clearly visible person is a primary subject; the face and a substantial upper body may not be cropped away. open: decide from Scene Description; keep staged presence for coherence; do not invent a person if Scene Description stages none.",
  "Priority, in this order: (1) Locked semantic invariants — eventMode, requiredSubjects, humanPresenceConstraint, Atom-named form. (2) Required relationship — comparison, decision, unresolved tension. (3) Production realization — crop, composition, camera, light, materials, wardrobe, environment. (4) Senior Director polish — may improve #3 only; may never weaken #1 or #2.",
  "Form versus finish: an Atom-named form is WHAT and must be kept. An unnamed form is HOW — choose it once in projectVisualContinuity and hold it for this Short. The form chosen in this expand holds on every plate, whether the Atom named it or production chose it. Do not write a category recipe.",
  "sceneDescription is the staged event, including any open question. Non-binding shortcuts are only camera, packshot, and lighting cliches — never the place, people, subjects, or action. You own the production treatment, not the story meaning. Do not paste the sentence. Do not paste narration. Do not dump camera syntax. Do not rewrite, paraphrase back, or return sceneDescription or situationLock.",
].join("\n");
