export const PRODUCTION_VISUAL_FINISH = [
  "Before choosing light and palette, derive the beat's mood from Purpose and the story's open or closed tension. Light character and temperature must serve that mood.",
  "Every plate states a purposeful lighting design: source and direction, hard or soft character, contrast and falloff, and subject/background separation. One light source described well beats three described loosely. Do not default to flat, even, unmotivated illumination.",
  "Establish a coherent palette and tonal hierarchy fit to the scene's Purpose: dominant temperature relationship, subject-versus-background separation, controlled contrast. No fixed colors from doctrine.",
  "Build a dimensional frame: foreground/midground/background relationship, subject-to-background distance, focus falloff. The background must stay readable as a real place at a glance: a named midground cue, stated subject-to-background distance, and focus falloff. Simplify clutter, not geography.",
  "Choose the environment's register deliberately from Purpose and the beat — ordinary, intimate, technical, institutional, documentary, aspirational, or premium — and dress the place to that register with non-claim cues. Premium is one register a director may choose, never the default aesthetic; an undirected beige room is equally a defect. One register per Short's visual world.",
  "State enough optical behavior to read as photography: shot distance, camera height, perspective, lens or focal-length character where useful, depth of field and focus priority — derived from the scene and Purpose, never a global recipe.",
  "Render visible materials believably: texture, specular/reflective response, translucency or roughness appropriate to what the scene actually shows. Hero physical products receive intentional, category-credible premium material and proportion treatment appropriate to what the story shows — weight, specular response, cap, and label stock — not an arbitrary generic default. When Scene Description names a generic, unbranded, or unlabeled hero product, unbranded means no logo, not cheap packaging. Do not invent matte plastic as the default just to be concrete. No fixed colors, forms, or packaging recipes from doctrine.",
  "Every plate names the hero object's material and finish explicitly. An unstated material invites a cheap generic default from the image tool.",
  "Vague quality words alone (\"high quality\", \"professional\", \"cinematic\") do not create finish — state the concrete visual conditions instead. Same anti-vibe rule as composition.",
  "Role/Purpose choose the visual language; not every scene is a glossy advertisement.",
  "Do not reuse one safe recipe (unmotivated soft key + featureless neutral void + centered subject) across scenes. Continuity locks the world and identity — not identical exposure, emphasis, or emptiness. Within one world, key ratio, contrast, and emphasis may shift per beat.",
].join("\n");
