/**
 * Compact operational extract of the YouTube Shorts Story Brain.
 * Canonical thought: ../brain/*.md — do not runtime-import Reference/.
 */
export const SHORTS_STORY_BRAIN = [
  "YouTube Shorts Story Brain (decide the story, then write scenes):",
  "The Atom gives facts, not wording. Rebuild every spoken line from scratch as you would say it to one person. Preserve the claim — never the sentence, and never the Atom's name for a thing: call each recurring thing by what the viewer sees or does with it, not by a compound noun.",
  "Spoken lock fields: write openingQuestion, payoff, beats[].job, and hookWhy as you would SAY them.",
  "Conflict rule 1: When the Atom takeaway or decision question is abstract and a concrete Atom-supported example would make the idea understandable, that example is the carrier. Teach the abstract idea THROUGH it. Extra examples that only repeat the same rule are excluded — they do not get their own scene, even if the Atom also names them. Use multiple examples only when the central story question is itself a comparison between those examples.",
  "Do not explain an abstraction for several scenes and only later reveal the concrete example that would have made it understandable from the beginning.",
  "Operating sequence: (1) treat the Atom as closed-world truth (2) fill storyArchitecture — the story you are telling (3) only then write EXACTLY 7 scenes that obey that lock. Story first. Scenes second. Do not invent facts.",
  "storyArchitecture must include: storyPromise; carrierMode (single | declared_comparison | none); primaryCarrier; comparisonCarriers; excludedCarriers; viewerOpening; hookMechanism; hookWhy; openingQuestion; scene1Withholds; payoff; beats[7] with sceneNumber + job + because (because required and nonempty on scenes 2–7).",
  "carrierMode single is the default when a usable concrete exists. declared_comparison only when the story question is a comparison of those supported examples. none only when the Atom has no concrete teaching example — do not invent one.",
  "Spoken first-hearing language: narration is a story a smart first-time listener can follow in one pass. Ordinary words first. One new idea per scene. Narration budget: at most 2 sentences and 22 words. A definition never travels with its implication — convert definitions into consequences. A fact appears only in the scene where it changes what the viewer understands, never earlier. Frame as a realization unfolding, not a verdict announced. Prefer the Atom’s strongest useful way of seeing the subject. Translate Atom research phrasing into spoken story — do not recite tension, desiredTakeaway, or decisionQuestion wording. If a technical term is required, explain it in the same breath. Speak to one viewer. Not a children's-show voice. Not a label-instructor voice.",
  "Spoken rewrite pairs (same transformation, different domains — copy the move, not the nouns): “The published arrival window is a carrier-defined interval, not proof both trips share the same clock.” → “Both can say tomorrow morning and still mean different hours.” “Confirm the declared scope before treating the two quotes as comparable.” → “Make sure both quotes cover the same work. Then compare the price.” “The dated event is not proof the two accounts describe the same turning point.” → “Same year on the page can still be two different stories.”",
  "Avoid these constructions: “X is not a Y”; “X is the unit/measure/term that…”; passive verdicts such as “is being judged”; three-technical-noun clauses. Internal planning may use precise analytical concepts. Spoken story must translate them. In spoken fields (narration, on-screen text, jobs, payoff, openingQuestion), avoid like-for-like, like with like, on that basis, fair basis. Say the consequence in ordinary words.",
  "Hook is a decision, not a catchy-line formula. Build Scene 1 from audience + customer moment + selected carrier + central tension. Answer: why should THIS audience care about THIS story in the first seconds?",
  "Hook decision procedure (required): (1) Name the real opening situation the viewer is already in. (2) Name the assumption, shortcut, or want that situation creates. (3) Choose the strongest truthful Atom-supported mechanism that opens a gap — unanswered question, assumption break, surprising supported distinction, expectation mismatch, or consequence/stakes the viewer already has. (4) Give enough context that the plot is understandable on first listen. (5) Withhold the resolution so Scene 2 has work to do. (6) Make the spoken line and the opening visual situation work together without duplicating each other. Write hookWhy as one sentence explaining why that mechanism fits this Atom and why it beat a truthful alternative. Mechanism is a free description, not an enum. Scene 1 may place the viewer inside the customer moment when the Atom’s moment supports it — an option, never a template. Hook compression: Scene 1 spoken line is at most two clauses. The opening question is the thought the viewer would have in that moment — not a document or label question.",
  "Context before cleverness. Immediate clear situation. One center of attention. A specific curiosity gap. Enough orientation to understand the plot. Withhold the resolution. Spoken line and opening visual work together without duplicating each other. No opaque tease. No vague clickbait. No reusable bargain-tease formula that ignores the selected carrier. If the opening would work for almost any comparison story after swapping nouns, rebuild it.",
  "Each beat after Scene 1 exists because the previous beat opened a problem, question, or incomplete understanding. Fill beats[].because on scenes 2–7 with that necessity. Therefore/but is required behavior, not a preference: answering the open question must open the next; only Scene 7 closes clean. Avoid and-then fact lists and takeaway checklists. Jobs are viewer-state story moves, not first-check / second-check / define-the-term labels. One connected story, not seven informational cards plus a summary.",
  "Write toward the ending: decide payoff before Scene 1 so Scene 7 resolves openingQuestion. Payoff must pass the retell test: one two-beat line — setup, then turn — a viewer could repeat to a friend tomorrow, using none of the Atom's nouns. Remove unnecessary payoff hedging. Make the ending decisive, but never strengthen the Atom’s claim. Prefer a direct rule over phrases such as “can actually” when the qualification adds no truth. The second payoff beat must add a new move, consequence, or decision — not merely restate the first beat. If both beats communicate the same idea, compress them. Noun repeat is allowed when it keeps the claim clear. Memorable Atom-supported takeaway. Do not fabricate advice.",
  "Narration speaks. Scene description shows a concrete visual situation with selective detail — not camera, lens, lighting, shot size, movement, or generation syntax. On-screen text labels or teases without spoiling Scene 1’s unresolved question. Do not make all three say the same thing.",
  "Each scene does one clear piece of story work for about seven seconds. Later scenes answer prior uncertainty or move toward payoff. Vary informational rhythm.",
  "storyRole remains a short flexible string. Line of Discovery may be a quality lens (discovery, reframe, payoff) — not a required seven-role schema. Never force a fixed Hook → Question → … → Payoff taxonomy. Never force Mistake, Framework, controversy, belief challenge, character, or fake conflict when the Atom does not support it.",
  "Visual embodiment may show a generic person or ordinary situation for the Atom-supported audience moment when that adds no new factual claim. Do not invent named customers, testimonials, medical outcomes, or fabricated drama as fact. Do not invent product-part locations, packaging geography, or store layout the Atom does not name. If the Atom names a panel or field, point to that. Do not invent where else a number lives.",
  "Before finishing: scenes must obey the lock; excludedCarriers must not appear as later-scene subjects; unsupported examples and subject drift must be removed. If a desired beat needs unsupported information, change the treatment.",
].join("\n");
